/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.lang.impl;

import eu.jgen.notes.dmw.lite.lang.DBBinaryOperation;
import eu.jgen.notes.dmw.lite.lang.DBExpression;
import eu.jgen.notes.dmw.lite.lang.LangFactory;
import eu.jgen.notes.dmw.lite.lang.LangPackage;
import eu.jgen.notes.dmw.lite.lang.XExpression;
import eu.jgen.notes.dmw.lite.lang.YAccessLevel;
import eu.jgen.notes.dmw.lite.lang.YAnnot;
import eu.jgen.notes.dmw.lite.lang.YAnnotAbstractColumn;
import eu.jgen.notes.dmw.lite.lang.YAnnotAction;
import eu.jgen.notes.dmw.lite.lang.YAnnotAttr;
import eu.jgen.notes.dmw.lite.lang.YAnnotColumn;
import eu.jgen.notes.dmw.lite.lang.YAnnotColumnLike;
import eu.jgen.notes.dmw.lite.lang.YAnnotDatabase;
import eu.jgen.notes.dmw.lite.lang.YAnnotDecimal;
import eu.jgen.notes.dmw.lite.lang.YAnnotDefault;
import eu.jgen.notes.dmw.lite.lang.YAnnotDefaultNumber;
import eu.jgen.notes.dmw.lite.lang.YAnnotDefaultText;
import eu.jgen.notes.dmw.lite.lang.YAnnotDefaultType;
import eu.jgen.notes.dmw.lite.lang.YAnnotEntity;
import eu.jgen.notes.dmw.lite.lang.YAnnotEntityInner;
import eu.jgen.notes.dmw.lite.lang.YAnnotForeignKey;
import eu.jgen.notes.dmw.lite.lang.YAnnotId;
import eu.jgen.notes.dmw.lite.lang.YAnnotIdInner;
import eu.jgen.notes.dmw.lite.lang.YAnnotJava;
import eu.jgen.notes.dmw.lite.lang.YAnnotLength;
import eu.jgen.notes.dmw.lite.lang.YAnnotMax;
import eu.jgen.notes.dmw.lite.lang.YAnnotMessage;
import eu.jgen.notes.dmw.lite.lang.YAnnotPrimaryKey;
import eu.jgen.notes.dmw.lite.lang.YAnnotRel;
import eu.jgen.notes.dmw.lite.lang.YAnnotSwift;
import eu.jgen.notes.dmw.lite.lang.YAnnotTable;
import eu.jgen.notes.dmw.lite.lang.YAnnotTechnicalDesign;
import eu.jgen.notes.dmw.lite.lang.YAnnotTop;
import eu.jgen.notes.dmw.lite.lang.YAssociateStatement;
import eu.jgen.notes.dmw.lite.lang.YClass;
import eu.jgen.notes.dmw.lite.lang.YCreateStatement;
import eu.jgen.notes.dmw.lite.lang.YDeleteStatement;
import eu.jgen.notes.dmw.lite.lang.YFunction;
import eu.jgen.notes.dmw.lite.lang.YJoin;
import eu.jgen.notes.dmw.lite.lang.YJoinDef;
import eu.jgen.notes.dmw.lite.lang.YMember;
import eu.jgen.notes.dmw.lite.lang.YPackageDeclaration;
import eu.jgen.notes.dmw.lite.lang.YProperty;
import eu.jgen.notes.dmw.lite.lang.YReadEachStatement;
import eu.jgen.notes.dmw.lite.lang.YReadStatement;
import eu.jgen.notes.dmw.lite.lang.YStructRefPair;
import eu.jgen.notes.dmw.lite.lang.YTuples;
import eu.jgen.notes.dmw.lite.lang.YUpdateStatement;
import eu.jgen.notes.dmw.lite.lang.YWhere;
import eu.jgen.notes.dmw.lite.lang.YWidget;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.eclipse.xtext.common.types.TypesPackage;

import org.eclipse.xtext.xbase.XbasePackage;

import org.eclipse.xtext.xtype.XtypePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class LangPackageImpl extends EPackageImpl implements LangPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yWidgetEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yPackageDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yClassEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yMemberEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yTuplesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yFunctionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yReadEachStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yUpdateStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yDeleteStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAssociateStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yStructRefPairEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yJoinEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yJoinDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotTopEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotDefaultTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotDefaultTextEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotDefaultNumberEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotEntityInnerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotEntityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotAttrEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotRelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotIdInnerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotIdEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotTechnicalDesignEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotTableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotColumnEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotColumnLikeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotAbstractColumnEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotPrimaryKeyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotForeignKeyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotJavaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotSwiftEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotDatabaseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dbExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yReadStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yCreateStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yWhereEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotLengthEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotMaxEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotDecimalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotDefaultEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yAnnotMessageEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dbBinaryOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum yAccessLevelEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private LangPackageImpl()
  {
    super(eNS_URI, LangFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link LangPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static LangPackage init()
  {
    if (isInited) return (LangPackage)EPackage.Registry.INSTANCE.getEPackage(LangPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredLangPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    LangPackageImpl theLangPackage = registeredLangPackage instanceof LangPackageImpl ? (LangPackageImpl)registeredLangPackage : new LangPackageImpl();

    isInited = true;

    // Initialize simple dependencies
    TypesPackage.eINSTANCE.eClass();
    XbasePackage.eINSTANCE.eClass();
    XtypePackage.eINSTANCE.eClass();

    // Create package meta-data objects
    theLangPackage.createPackageContents();

    // Initialize created meta-data
    theLangPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theLangPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(LangPackage.eNS_URI, theLangPackage);
    return theLangPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYWidget()
  {
    return yWidgetEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYWidget_Package()
  {
    return (EReference)yWidgetEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYWidget_ImportSection()
  {
    return (EReference)yWidgetEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYWidget_Annotations()
  {
    return (EReference)yWidgetEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYWidget_Classes()
  {
    return (EReference)yWidgetEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYPackageDeclaration()
  {
    return yPackageDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYPackageDeclaration_Name()
  {
    return (EAttribute)yPackageDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYClass()
  {
    return yClassEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYClass_Superclass()
  {
    return (EReference)yClassEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYClass_EntityRef()
  {
    return (EReference)yClassEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYClass_Members()
  {
    return (EReference)yClassEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYMember()
  {
    return yMemberEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYMember_Name()
  {
    return (EAttribute)yMemberEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYProperty()
  {
    return yPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYProperty_Access()
  {
    return (EAttribute)yPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYProperty_Type()
  {
    return (EReference)yPropertyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYProperty_Tuples()
  {
    return (EReference)yPropertyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYProperty_Optional()
  {
    return (EAttribute)yPropertyEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYProperty_AttrRef()
  {
    return (EReference)yPropertyEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYProperty_Annotations()
  {
    return (EReference)yPropertyEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYTuples()
  {
    return yTuplesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYTuples_Includes()
  {
    return (EReference)yTuplesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYFunction()
  {
    return yFunctionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYFunction_Access()
  {
    return (EAttribute)yFunctionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYFunction_Params()
  {
    return (EReference)yFunctionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYFunction_Type()
  {
    return (EReference)yFunctionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYFunction_Body()
  {
    return (EReference)yFunctionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getXExpression()
  {
    return xExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYReadEachStatement()
  {
    return yReadEachStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadEachStatement_Structs()
  {
    return (EReference)yReadEachStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadEachStatement_Joinclause()
  {
    return (EReference)yReadEachStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadEachStatement_Whereclause()
  {
    return (EReference)yReadEachStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadEachStatement_Target()
  {
    return (EReference)yReadEachStatementEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadEachStatement_Success()
  {
    return (EReference)yReadEachStatementEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYUpdateStatement()
  {
    return yUpdateStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYUpdateStatement_Struct()
  {
    return (EReference)yUpdateStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYUpdateStatement_SetBlock()
  {
    return (EReference)yUpdateStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYUpdateStatement_Success()
  {
    return (EReference)yUpdateStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYDeleteStatement()
  {
    return yDeleteStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYDeleteStatement_Struct()
  {
    return (EReference)yDeleteStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAssociateStatement()
  {
    return yAssociateStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAssociateStatement_Joinref()
  {
    return (EReference)yAssociateStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYStructRefPair()
  {
    return yStructRefPairEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYStructRefPair_Structproperty()
  {
    return (EReference)yStructRefPairEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYStructRefPair_Structclass()
  {
    return (EReference)yStructRefPairEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYJoin()
  {
    return yJoinEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYJoin_Joindefs()
  {
    return (EReference)yJoinEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYJoinDef()
  {
    return yJoinDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYJoinDef_FromView()
  {
    return (EReference)yJoinDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYJoinDef_RelRef()
  {
    return (EReference)yJoinDefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYJoinDef_ToView()
  {
    return (EReference)yJoinDefEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnot()
  {
    return yAnnotEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnot_Type()
  {
    return (EReference)yAnnotEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnot_Msgtype()
  {
    return (EAttribute)yAnnotEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotTop()
  {
    return yAnnotTopEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotTop_Type()
  {
    return (EReference)yAnnotTopEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotDefaultType()
  {
    return yAnnotDefaultTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotDefaultText()
  {
    return yAnnotDefaultTextEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotDefaultText_Value()
  {
    return (EAttribute)yAnnotDefaultTextEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotDefaultNumber()
  {
    return yAnnotDefaultNumberEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotDefaultNumber_Value()
  {
    return (EAttribute)yAnnotDefaultNumberEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotEntityInner()
  {
    return yAnnotEntityInnerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotEntity()
  {
    return yAnnotEntityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotEntity_Name()
  {
    return (EAttribute)yAnnotEntityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotEntity_Superannot()
  {
    return (EReference)yAnnotEntityEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotEntity_Annots()
  {
    return (EReference)yAnnotEntityEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotAttr()
  {
    return yAnnotAttrEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotAttr_Name()
  {
    return (EAttribute)yAnnotAttrEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotAttr_Yclass()
  {
    return (EReference)yAnnotAttrEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotAttr_Optional()
  {
    return (EAttribute)yAnnotAttrEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotAttr_Annots()
  {
    return (EReference)yAnnotAttrEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotRel()
  {
    return yAnnotRelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotRel_Parent()
  {
    return (EAttribute)yAnnotRelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotRel_Name()
  {
    return (EAttribute)yAnnotRelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotRel_Optional()
  {
    return (EAttribute)yAnnotRelEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotRel_Target()
  {
    return (EReference)yAnnotRelEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotRel_Many()
  {
    return (EAttribute)yAnnotRelEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotRel_Inverse()
  {
    return (EReference)yAnnotRelEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotIdInner()
  {
    return yAnnotIdInnerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotId()
  {
    return yAnnotIdEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotId_Name()
  {
    return (EAttribute)yAnnotIdEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotId_Annots()
  {
    return (EReference)yAnnotIdEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotTechnicalDesign()
  {
    return yAnnotTechnicalDesignEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotTechnicalDesign_Database()
  {
    return (EReference)yAnnotTechnicalDesignEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotTechnicalDesign_Features()
  {
    return (EReference)yAnnotTechnicalDesignEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotTable()
  {
    return yAnnotTableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotTable_Name()
  {
    return (EAttribute)yAnnotTableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotTable_Entityref()
  {
    return (EReference)yAnnotTableEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotTable_Columns()
  {
    return (EReference)yAnnotTableEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotTable_Primarykey()
  {
    return (EReference)yAnnotTableEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotTable_Foreignkeys()
  {
    return (EReference)yAnnotTableEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotColumn()
  {
    return yAnnotColumnEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotColumn_Attrref()
  {
    return (EReference)yAnnotColumnEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotColumn_Type()
  {
    return (EAttribute)yAnnotColumnEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotColumn_Optional()
  {
    return (EAttribute)yAnnotColumnEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotColumn_Annots()
  {
    return (EReference)yAnnotColumnEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotColumnLike()
  {
    return yAnnotColumnLikeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotColumnLike_Columnref()
  {
    return (EReference)yAnnotColumnLikeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotAbstractColumn()
  {
    return yAnnotAbstractColumnEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotAbstractColumn_Name()
  {
    return (EAttribute)yAnnotAbstractColumnEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotAbstractColumn_Type()
  {
    return (EReference)yAnnotAbstractColumnEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotPrimaryKey()
  {
    return yAnnotPrimaryKeyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotPrimaryKey_Columns()
  {
    return (EReference)yAnnotPrimaryKeyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotForeignKey()
  {
    return yAnnotForeignKeyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotForeignKey_Relationship()
  {
    return (EReference)yAnnotForeignKeyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotForeignKey_Columns()
  {
    return (EReference)yAnnotForeignKeyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotJava()
  {
    return yAnnotJavaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotJava_Database()
  {
    return (EReference)yAnnotJavaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotSwift()
  {
    return yAnnotSwiftEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotSwift_Name()
  {
    return (EAttribute)yAnnotSwiftEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYAnnotSwift_Database()
  {
    return (EReference)yAnnotSwiftEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotDatabase()
  {
    return yAnnotDatabaseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotDatabase_Name()
  {
    return (EAttribute)yAnnotDatabaseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDBExpression()
  {
    return dbExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDBExpression_LeftOperand()
  {
    return (EReference)dbExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDBExpression_RightOperand()
  {
    return (EReference)dbExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYReadStatement()
  {
    return yReadStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadStatement_Structs()
  {
    return (EReference)yReadStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadStatement_Joinclause()
  {
    return (EReference)yReadStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadStatement_Whereclause()
  {
    return (EReference)yReadStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadStatement_SuccessExpressions()
  {
    return (EReference)yReadStatementEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYReadStatement_NotfoundExpressions()
  {
    return (EReference)yReadStatementEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYCreateStatement()
  {
    return yCreateStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYCreateStatement_Struct()
  {
    return (EReference)yCreateStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYCreateStatement_SetExpressions()
  {
    return (EReference)yCreateStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYCreateStatement_SuccessExpressions()
  {
    return (EReference)yCreateStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYCreateStatement_AlreadyExistExpressions()
  {
    return (EReference)yCreateStatementEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYWhere()
  {
    return yWhereEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getYWhere_Expression()
  {
    return (EReference)yWhereEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotLength()
  {
    return yAnnotLengthEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotLength_Length()
  {
    return (EAttribute)yAnnotLengthEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotMax()
  {
    return yAnnotMaxEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotMax_Length()
  {
    return (EAttribute)yAnnotMaxEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotDecimal()
  {
    return yAnnotDecimalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotDecimal_Length()
  {
    return (EAttribute)yAnnotDecimalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotDecimal_Decimal()
  {
    return (EAttribute)yAnnotDecimalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotDefault()
  {
    return yAnnotDefaultEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotAction()
  {
    return yAnnotActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotAction_Action()
  {
    return (EAttribute)yAnnotActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getYAnnotMessage()
  {
    return yAnnotMessageEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getYAnnotMessage_Msg()
  {
    return (EAttribute)yAnnotMessageEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDBBinaryOperation()
  {
    return dbBinaryOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDBBinaryOperation_Feature()
  {
    return (EReference)dbBinaryOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getYAccessLevel()
  {
    return yAccessLevelEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LangFactory getLangFactory()
  {
    return (LangFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    yWidgetEClass = createEClass(YWIDGET);
    createEReference(yWidgetEClass, YWIDGET__PACKAGE);
    createEReference(yWidgetEClass, YWIDGET__IMPORT_SECTION);
    createEReference(yWidgetEClass, YWIDGET__ANNOTATIONS);
    createEReference(yWidgetEClass, YWIDGET__CLASSES);

    yPackageDeclarationEClass = createEClass(YPACKAGE_DECLARATION);
    createEAttribute(yPackageDeclarationEClass, YPACKAGE_DECLARATION__NAME);

    yClassEClass = createEClass(YCLASS);
    createEReference(yClassEClass, YCLASS__SUPERCLASS);
    createEReference(yClassEClass, YCLASS__ENTITY_REF);
    createEReference(yClassEClass, YCLASS__MEMBERS);

    yMemberEClass = createEClass(YMEMBER);
    createEAttribute(yMemberEClass, YMEMBER__NAME);

    yPropertyEClass = createEClass(YPROPERTY);
    createEAttribute(yPropertyEClass, YPROPERTY__ACCESS);
    createEReference(yPropertyEClass, YPROPERTY__TYPE);
    createEReference(yPropertyEClass, YPROPERTY__TUPLES);
    createEAttribute(yPropertyEClass, YPROPERTY__OPTIONAL);
    createEReference(yPropertyEClass, YPROPERTY__ATTR_REF);
    createEReference(yPropertyEClass, YPROPERTY__ANNOTATIONS);

    yTuplesEClass = createEClass(YTUPLES);
    createEReference(yTuplesEClass, YTUPLES__INCLUDES);

    yFunctionEClass = createEClass(YFUNCTION);
    createEAttribute(yFunctionEClass, YFUNCTION__ACCESS);
    createEReference(yFunctionEClass, YFUNCTION__PARAMS);
    createEReference(yFunctionEClass, YFUNCTION__TYPE);
    createEReference(yFunctionEClass, YFUNCTION__BODY);

    xExpressionEClass = createEClass(XEXPRESSION);

    yReadEachStatementEClass = createEClass(YREAD_EACH_STATEMENT);
    createEReference(yReadEachStatementEClass, YREAD_EACH_STATEMENT__STRUCTS);
    createEReference(yReadEachStatementEClass, YREAD_EACH_STATEMENT__JOINCLAUSE);
    createEReference(yReadEachStatementEClass, YREAD_EACH_STATEMENT__WHERECLAUSE);
    createEReference(yReadEachStatementEClass, YREAD_EACH_STATEMENT__TARGET);
    createEReference(yReadEachStatementEClass, YREAD_EACH_STATEMENT__SUCCESS);

    yUpdateStatementEClass = createEClass(YUPDATE_STATEMENT);
    createEReference(yUpdateStatementEClass, YUPDATE_STATEMENT__STRUCT);
    createEReference(yUpdateStatementEClass, YUPDATE_STATEMENT__SET_BLOCK);
    createEReference(yUpdateStatementEClass, YUPDATE_STATEMENT__SUCCESS);

    yDeleteStatementEClass = createEClass(YDELETE_STATEMENT);
    createEReference(yDeleteStatementEClass, YDELETE_STATEMENT__STRUCT);

    yAssociateStatementEClass = createEClass(YASSOCIATE_STATEMENT);
    createEReference(yAssociateStatementEClass, YASSOCIATE_STATEMENT__JOINREF);

    yStructRefPairEClass = createEClass(YSTRUCT_REF_PAIR);
    createEReference(yStructRefPairEClass, YSTRUCT_REF_PAIR__STRUCTPROPERTY);
    createEReference(yStructRefPairEClass, YSTRUCT_REF_PAIR__STRUCTCLASS);

    yJoinEClass = createEClass(YJOIN);
    createEReference(yJoinEClass, YJOIN__JOINDEFS);

    yJoinDefEClass = createEClass(YJOIN_DEF);
    createEReference(yJoinDefEClass, YJOIN_DEF__FROM_VIEW);
    createEReference(yJoinDefEClass, YJOIN_DEF__REL_REF);
    createEReference(yJoinDefEClass, YJOIN_DEF__TO_VIEW);

    yAnnotEClass = createEClass(YANNOT);
    createEReference(yAnnotEClass, YANNOT__TYPE);
    createEAttribute(yAnnotEClass, YANNOT__MSGTYPE);

    yAnnotTopEClass = createEClass(YANNOT_TOP);
    createEReference(yAnnotTopEClass, YANNOT_TOP__TYPE);

    yAnnotDefaultTypeEClass = createEClass(YANNOT_DEFAULT_TYPE);

    yAnnotDefaultTextEClass = createEClass(YANNOT_DEFAULT_TEXT);
    createEAttribute(yAnnotDefaultTextEClass, YANNOT_DEFAULT_TEXT__VALUE);

    yAnnotDefaultNumberEClass = createEClass(YANNOT_DEFAULT_NUMBER);
    createEAttribute(yAnnotDefaultNumberEClass, YANNOT_DEFAULT_NUMBER__VALUE);

    yAnnotEntityInnerEClass = createEClass(YANNOT_ENTITY_INNER);

    yAnnotEntityEClass = createEClass(YANNOT_ENTITY);
    createEAttribute(yAnnotEntityEClass, YANNOT_ENTITY__NAME);
    createEReference(yAnnotEntityEClass, YANNOT_ENTITY__SUPERANNOT);
    createEReference(yAnnotEntityEClass, YANNOT_ENTITY__ANNOTS);

    yAnnotAttrEClass = createEClass(YANNOT_ATTR);
    createEAttribute(yAnnotAttrEClass, YANNOT_ATTR__NAME);
    createEReference(yAnnotAttrEClass, YANNOT_ATTR__YCLASS);
    createEAttribute(yAnnotAttrEClass, YANNOT_ATTR__OPTIONAL);
    createEReference(yAnnotAttrEClass, YANNOT_ATTR__ANNOTS);

    yAnnotRelEClass = createEClass(YANNOT_REL);
    createEAttribute(yAnnotRelEClass, YANNOT_REL__PARENT);
    createEAttribute(yAnnotRelEClass, YANNOT_REL__NAME);
    createEAttribute(yAnnotRelEClass, YANNOT_REL__OPTIONAL);
    createEReference(yAnnotRelEClass, YANNOT_REL__TARGET);
    createEAttribute(yAnnotRelEClass, YANNOT_REL__MANY);
    createEReference(yAnnotRelEClass, YANNOT_REL__INVERSE);

    yAnnotIdInnerEClass = createEClass(YANNOT_ID_INNER);

    yAnnotIdEClass = createEClass(YANNOT_ID);
    createEAttribute(yAnnotIdEClass, YANNOT_ID__NAME);
    createEReference(yAnnotIdEClass, YANNOT_ID__ANNOTS);

    yAnnotTechnicalDesignEClass = createEClass(YANNOT_TECHNICAL_DESIGN);
    createEReference(yAnnotTechnicalDesignEClass, YANNOT_TECHNICAL_DESIGN__DATABASE);
    createEReference(yAnnotTechnicalDesignEClass, YANNOT_TECHNICAL_DESIGN__FEATURES);

    yAnnotTableEClass = createEClass(YANNOT_TABLE);
    createEAttribute(yAnnotTableEClass, YANNOT_TABLE__NAME);
    createEReference(yAnnotTableEClass, YANNOT_TABLE__ENTITYREF);
    createEReference(yAnnotTableEClass, YANNOT_TABLE__COLUMNS);
    createEReference(yAnnotTableEClass, YANNOT_TABLE__PRIMARYKEY);
    createEReference(yAnnotTableEClass, YANNOT_TABLE__FOREIGNKEYS);

    yAnnotColumnEClass = createEClass(YANNOT_COLUMN);
    createEReference(yAnnotColumnEClass, YANNOT_COLUMN__ATTRREF);
    createEAttribute(yAnnotColumnEClass, YANNOT_COLUMN__TYPE);
    createEAttribute(yAnnotColumnEClass, YANNOT_COLUMN__OPTIONAL);
    createEReference(yAnnotColumnEClass, YANNOT_COLUMN__ANNOTS);

    yAnnotColumnLikeEClass = createEClass(YANNOT_COLUMN_LIKE);
    createEReference(yAnnotColumnLikeEClass, YANNOT_COLUMN_LIKE__COLUMNREF);

    yAnnotAbstractColumnEClass = createEClass(YANNOT_ABSTRACT_COLUMN);
    createEAttribute(yAnnotAbstractColumnEClass, YANNOT_ABSTRACT_COLUMN__NAME);
    createEReference(yAnnotAbstractColumnEClass, YANNOT_ABSTRACT_COLUMN__TYPE);

    yAnnotPrimaryKeyEClass = createEClass(YANNOT_PRIMARY_KEY);
    createEReference(yAnnotPrimaryKeyEClass, YANNOT_PRIMARY_KEY__COLUMNS);

    yAnnotForeignKeyEClass = createEClass(YANNOT_FOREIGN_KEY);
    createEReference(yAnnotForeignKeyEClass, YANNOT_FOREIGN_KEY__RELATIONSHIP);
    createEReference(yAnnotForeignKeyEClass, YANNOT_FOREIGN_KEY__COLUMNS);

    yAnnotJavaEClass = createEClass(YANNOT_JAVA);
    createEReference(yAnnotJavaEClass, YANNOT_JAVA__DATABASE);

    yAnnotSwiftEClass = createEClass(YANNOT_SWIFT);
    createEAttribute(yAnnotSwiftEClass, YANNOT_SWIFT__NAME);
    createEReference(yAnnotSwiftEClass, YANNOT_SWIFT__DATABASE);

    yAnnotDatabaseEClass = createEClass(YANNOT_DATABASE);
    createEAttribute(yAnnotDatabaseEClass, YANNOT_DATABASE__NAME);

    dbExpressionEClass = createEClass(DB_EXPRESSION);
    createEReference(dbExpressionEClass, DB_EXPRESSION__LEFT_OPERAND);
    createEReference(dbExpressionEClass, DB_EXPRESSION__RIGHT_OPERAND);

    yReadStatementEClass = createEClass(YREAD_STATEMENT);
    createEReference(yReadStatementEClass, YREAD_STATEMENT__STRUCTS);
    createEReference(yReadStatementEClass, YREAD_STATEMENT__JOINCLAUSE);
    createEReference(yReadStatementEClass, YREAD_STATEMENT__WHERECLAUSE);
    createEReference(yReadStatementEClass, YREAD_STATEMENT__SUCCESS_EXPRESSIONS);
    createEReference(yReadStatementEClass, YREAD_STATEMENT__NOTFOUND_EXPRESSIONS);

    yCreateStatementEClass = createEClass(YCREATE_STATEMENT);
    createEReference(yCreateStatementEClass, YCREATE_STATEMENT__STRUCT);
    createEReference(yCreateStatementEClass, YCREATE_STATEMENT__SET_EXPRESSIONS);
    createEReference(yCreateStatementEClass, YCREATE_STATEMENT__SUCCESS_EXPRESSIONS);
    createEReference(yCreateStatementEClass, YCREATE_STATEMENT__ALREADY_EXIST_EXPRESSIONS);

    yWhereEClass = createEClass(YWHERE);
    createEReference(yWhereEClass, YWHERE__EXPRESSION);

    yAnnotLengthEClass = createEClass(YANNOT_LENGTH);
    createEAttribute(yAnnotLengthEClass, YANNOT_LENGTH__LENGTH);

    yAnnotMaxEClass = createEClass(YANNOT_MAX);
    createEAttribute(yAnnotMaxEClass, YANNOT_MAX__LENGTH);

    yAnnotDecimalEClass = createEClass(YANNOT_DECIMAL);
    createEAttribute(yAnnotDecimalEClass, YANNOT_DECIMAL__LENGTH);
    createEAttribute(yAnnotDecimalEClass, YANNOT_DECIMAL__DECIMAL);

    yAnnotDefaultEClass = createEClass(YANNOT_DEFAULT);

    yAnnotActionEClass = createEClass(YANNOT_ACTION);
    createEAttribute(yAnnotActionEClass, YANNOT_ACTION__ACTION);

    yAnnotMessageEClass = createEClass(YANNOT_MESSAGE);
    createEAttribute(yAnnotMessageEClass, YANNOT_MESSAGE__MSG);

    dbBinaryOperationEClass = createEClass(DB_BINARY_OPERATION);
    createEReference(dbBinaryOperationEClass, DB_BINARY_OPERATION__FEATURE);

    // Create enums
    yAccessLevelEEnum = createEEnum(YACCESS_LEVEL);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    XtypePackage theXtypePackage = (XtypePackage)EPackage.Registry.INSTANCE.getEPackage(XtypePackage.eNS_URI);
    TypesPackage theTypesPackage = (TypesPackage)EPackage.Registry.INSTANCE.getEPackage(TypesPackage.eNS_URI);
    XbasePackage theXbasePackage = (XbasePackage)EPackage.Registry.INSTANCE.getEPackage(XbasePackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    yClassEClass.getESuperTypes().add(this.getYMember());
    yPropertyEClass.getESuperTypes().add(this.getYMember());
    yFunctionEClass.getESuperTypes().add(this.getYMember());
    xExpressionEClass.getESuperTypes().add(theXbasePackage.getXExpression());
    yReadEachStatementEClass.getESuperTypes().add(theXbasePackage.getXExpression());
    yUpdateStatementEClass.getESuperTypes().add(theXbasePackage.getXExpression());
    yDeleteStatementEClass.getESuperTypes().add(theXbasePackage.getXExpression());
    yAnnotDefaultTextEClass.getESuperTypes().add(this.getYAnnotDefaultType());
    yAnnotDefaultNumberEClass.getESuperTypes().add(this.getYAnnotDefaultType());
    yAnnotAttrEClass.getESuperTypes().add(this.getYAnnotEntityInner());
    yAnnotAttrEClass.getESuperTypes().add(this.getYAnnotIdInner());
    yAnnotRelEClass.getESuperTypes().add(this.getYAnnotEntityInner());
    yAnnotRelEClass.getESuperTypes().add(this.getYAnnotIdInner());
    yAnnotIdEClass.getESuperTypes().add(this.getYAnnotEntityInner());
    yReadStatementEClass.getESuperTypes().add(this.getXExpression());
    yCreateStatementEClass.getESuperTypes().add(this.getXExpression());
    yWhereEClass.getESuperTypes().add(this.getXExpression());
    yAnnotLengthEClass.getESuperTypes().add(this.getYAnnot());
    yAnnotMaxEClass.getESuperTypes().add(this.getYAnnot());
    yAnnotDecimalEClass.getESuperTypes().add(this.getYAnnot());
    yAnnotDefaultEClass.getESuperTypes().add(this.getYAnnot());
    yAnnotActionEClass.getESuperTypes().add(this.getYAnnot());
    yAnnotMessageEClass.getESuperTypes().add(this.getYAnnot());
    dbBinaryOperationEClass.getESuperTypes().add(this.getDBExpression());

    // Initialize classes and features; add operations and parameters
    initEClass(yWidgetEClass, YWidget.class, "YWidget", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYWidget_Package(), this.getYPackageDeclaration(), null, "package", null, 0, 1, YWidget.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYWidget_ImportSection(), theXtypePackage.getXImportSection(), null, "importSection", null, 0, 1, YWidget.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYWidget_Annotations(), this.getYAnnotTop(), null, "annotations", null, 0, -1, YWidget.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYWidget_Classes(), this.getYClass(), null, "classes", null, 0, -1, YWidget.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yPackageDeclarationEClass, YPackageDeclaration.class, "YPackageDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYPackageDeclaration_Name(), ecorePackage.getEString(), "name", null, 0, 1, YPackageDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yClassEClass, YClass.class, "YClass", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYClass_Superclass(), theTypesPackage.getJvmTypeReference(), null, "superclass", null, 0, 1, YClass.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYClass_EntityRef(), this.getYAnnotEntity(), null, "entityRef", null, 0, 1, YClass.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYClass_Members(), this.getYMember(), null, "members", null, 0, -1, YClass.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yMemberEClass, YMember.class, "YMember", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYMember_Name(), ecorePackage.getEString(), "name", null, 0, 1, YMember.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yPropertyEClass, YProperty.class, "YProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYProperty_Access(), this.getYAccessLevel(), "access", null, 0, 1, YProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYProperty_Type(), theTypesPackage.getJvmTypeReference(), null, "type", null, 0, 1, YProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYProperty_Tuples(), this.getYTuples(), null, "tuples", null, 0, 1, YProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYProperty_Optional(), ecorePackage.getEBoolean(), "optional", null, 0, 1, YProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYProperty_AttrRef(), this.getYAnnotAttr(), null, "attrRef", null, 0, 1, YProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYProperty_Annotations(), this.getYAnnot(), null, "annotations", null, 0, -1, YProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yTuplesEClass, YTuples.class, "YTuples", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYTuples_Includes(), this.getYProperty(), null, "includes", null, 0, -1, YTuples.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yFunctionEClass, YFunction.class, "YFunction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYFunction_Access(), this.getYAccessLevel(), "access", null, 0, 1, YFunction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYFunction_Params(), theTypesPackage.getJvmTypeReference(), null, "params", null, 0, -1, YFunction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYFunction_Type(), theTypesPackage.getJvmTypeReference(), null, "type", null, 0, 1, YFunction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYFunction_Body(), theXbasePackage.getXExpression(), null, "body", null, 0, 1, YFunction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xExpressionEClass, XExpression.class, "XExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(yReadEachStatementEClass, YReadEachStatement.class, "YReadEachStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYReadEachStatement_Structs(), this.getYStructRefPair(), null, "structs", null, 0, -1, YReadEachStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadEachStatement_Joinclause(), this.getYJoin(), null, "joinclause", null, 0, 1, YReadEachStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadEachStatement_Whereclause(), theXbasePackage.getXExpression(), null, "whereclause", null, 0, 1, YReadEachStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadEachStatement_Target(), this.getYProperty(), null, "target", null, 0, 1, YReadEachStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadEachStatement_Success(), theXbasePackage.getXExpression(), null, "success", null, 0, 1, YReadEachStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yUpdateStatementEClass, YUpdateStatement.class, "YUpdateStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYUpdateStatement_Struct(), this.getYStructRefPair(), null, "struct", null, 0, 1, YUpdateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYUpdateStatement_SetBlock(), theXbasePackage.getXExpression(), null, "setBlock", null, 0, 1, YUpdateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYUpdateStatement_Success(), theXbasePackage.getXExpression(), null, "success", null, 0, 1, YUpdateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yDeleteStatementEClass, YDeleteStatement.class, "YDeleteStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYDeleteStatement_Struct(), this.getYStructRefPair(), null, "struct", null, 0, 1, YDeleteStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAssociateStatementEClass, YAssociateStatement.class, "YAssociateStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYAssociateStatement_Joinref(), this.getYJoinDef(), null, "joinref", null, 0, 1, YAssociateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yStructRefPairEClass, YStructRefPair.class, "YStructRefPair", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYStructRefPair_Structproperty(), this.getYProperty(), null, "structproperty", null, 0, 1, YStructRefPair.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYStructRefPair_Structclass(), this.getYAnnotEntity(), null, "structclass", null, 0, 1, YStructRefPair.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yJoinEClass, YJoin.class, "YJoin", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYJoin_Joindefs(), this.getYJoinDef(), null, "joindefs", null, 0, -1, YJoin.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yJoinDefEClass, YJoinDef.class, "YJoinDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYJoinDef_FromView(), this.getYProperty(), null, "fromView", null, 0, 1, YJoinDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYJoinDef_RelRef(), this.getYAnnotRel(), null, "relRef", null, 0, 1, YJoinDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYJoinDef_ToView(), this.getYProperty(), null, "toView", null, 0, 1, YJoinDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotEClass, YAnnot.class, "YAnnot", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYAnnot_Type(), ecorePackage.getEObject(), null, "type", null, 0, 1, YAnnot.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYAnnot_Msgtype(), ecorePackage.getEString(), "msgtype", null, 0, 1, YAnnot.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotTopEClass, YAnnotTop.class, "YAnnotTop", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYAnnotTop_Type(), ecorePackage.getEObject(), null, "type", null, 0, 1, YAnnotTop.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotDefaultTypeEClass, YAnnotDefaultType.class, "YAnnotDefaultType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(yAnnotDefaultTextEClass, YAnnotDefaultText.class, "YAnnotDefaultText", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotDefaultText_Value(), ecorePackage.getEString(), "value", null, 0, 1, YAnnotDefaultText.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotDefaultNumberEClass, YAnnotDefaultNumber.class, "YAnnotDefaultNumber", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotDefaultNumber_Value(), ecorePackage.getEInt(), "value", null, 0, 1, YAnnotDefaultNumber.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotEntityInnerEClass, YAnnotEntityInner.class, "YAnnotEntityInner", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(yAnnotEntityEClass, YAnnotEntity.class, "YAnnotEntity", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotEntity_Name(), ecorePackage.getEString(), "name", null, 0, 1, YAnnotEntity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotEntity_Superannot(), this.getYAnnotEntity(), null, "superannot", null, 0, 1, YAnnotEntity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotEntity_Annots(), this.getYAnnotEntityInner(), null, "annots", null, 0, -1, YAnnotEntity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotAttrEClass, YAnnotAttr.class, "YAnnotAttr", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotAttr_Name(), ecorePackage.getEString(), "name", null, 0, 1, YAnnotAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotAttr_Yclass(), theTypesPackage.getJvmTypeReference(), null, "yclass", null, 0, 1, YAnnotAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYAnnotAttr_Optional(), ecorePackage.getEString(), "optional", null, 0, 1, YAnnotAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotAttr_Annots(), this.getYAnnot(), null, "annots", null, 0, -1, YAnnotAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotRelEClass, YAnnotRel.class, "YAnnotRel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotRel_Parent(), ecorePackage.getEBoolean(), "parent", null, 0, 1, YAnnotRel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYAnnotRel_Name(), ecorePackage.getEString(), "name", null, 0, 1, YAnnotRel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYAnnotRel_Optional(), ecorePackage.getEBoolean(), "optional", null, 0, 1, YAnnotRel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotRel_Target(), this.getYAnnotEntity(), null, "target", null, 0, 1, YAnnotRel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYAnnotRel_Many(), ecorePackage.getEBoolean(), "many", null, 0, 1, YAnnotRel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotRel_Inverse(), this.getYAnnotRel(), null, "inverse", null, 0, 1, YAnnotRel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotIdInnerEClass, YAnnotIdInner.class, "YAnnotIdInner", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(yAnnotIdEClass, YAnnotId.class, "YAnnotId", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotId_Name(), ecorePackage.getEString(), "name", null, 0, 1, YAnnotId.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotId_Annots(), this.getYAnnotEntityInner(), null, "annots", null, 0, -1, YAnnotId.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotTechnicalDesignEClass, YAnnotTechnicalDesign.class, "YAnnotTechnicalDesign", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYAnnotTechnicalDesign_Database(), this.getYAnnotDatabase(), null, "database", null, 0, 1, YAnnotTechnicalDesign.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotTechnicalDesign_Features(), this.getYAnnotTable(), null, "features", null, 0, -1, YAnnotTechnicalDesign.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotTableEClass, YAnnotTable.class, "YAnnotTable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotTable_Name(), ecorePackage.getEString(), "name", null, 0, 1, YAnnotTable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotTable_Entityref(), this.getYAnnotEntity(), null, "entityref", null, 0, 1, YAnnotTable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotTable_Columns(), this.getYAnnotAbstractColumn(), null, "columns", null, 0, -1, YAnnotTable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotTable_Primarykey(), this.getYAnnotPrimaryKey(), null, "primarykey", null, 0, 1, YAnnotTable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotTable_Foreignkeys(), this.getYAnnotForeignKey(), null, "foreignkeys", null, 0, -1, YAnnotTable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotColumnEClass, YAnnotColumn.class, "YAnnotColumn", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYAnnotColumn_Attrref(), this.getYAnnotAttr(), null, "attrref", null, 0, 1, YAnnotColumn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYAnnotColumn_Type(), ecorePackage.getEString(), "type", null, 0, 1, YAnnotColumn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYAnnotColumn_Optional(), ecorePackage.getEString(), "optional", null, 0, 1, YAnnotColumn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotColumn_Annots(), this.getYAnnot(), null, "annots", null, 0, -1, YAnnotColumn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotColumnLikeEClass, YAnnotColumnLike.class, "YAnnotColumnLike", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYAnnotColumnLike_Columnref(), this.getYAnnotAbstractColumn(), null, "columnref", null, 0, 1, YAnnotColumnLike.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotAbstractColumnEClass, YAnnotAbstractColumn.class, "YAnnotAbstractColumn", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotAbstractColumn_Name(), ecorePackage.getEString(), "name", null, 0, 1, YAnnotAbstractColumn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotAbstractColumn_Type(), ecorePackage.getEObject(), null, "type", null, 0, 1, YAnnotAbstractColumn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotPrimaryKeyEClass, YAnnotPrimaryKey.class, "YAnnotPrimaryKey", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYAnnotPrimaryKey_Columns(), this.getYAnnotAbstractColumn(), null, "columns", null, 0, -1, YAnnotPrimaryKey.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotForeignKeyEClass, YAnnotForeignKey.class, "YAnnotForeignKey", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYAnnotForeignKey_Relationship(), this.getYAnnotRel(), null, "relationship", null, 0, 1, YAnnotForeignKey.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotForeignKey_Columns(), this.getYAnnotAbstractColumn(), null, "columns", null, 0, -1, YAnnotForeignKey.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotJavaEClass, YAnnotJava.class, "YAnnotJava", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYAnnotJava_Database(), this.getYAnnotDatabase(), null, "database", null, 0, 1, YAnnotJava.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotSwiftEClass, YAnnotSwift.class, "YAnnotSwift", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotSwift_Name(), ecorePackage.getEString(), "name", null, 0, 1, YAnnotSwift.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYAnnotSwift_Database(), this.getYAnnotDatabase(), null, "database", null, 0, 1, YAnnotSwift.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotDatabaseEClass, YAnnotDatabase.class, "YAnnotDatabase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotDatabase_Name(), ecorePackage.getEString(), "name", null, 0, 1, YAnnotDatabase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dbExpressionEClass, DBExpression.class, "DBExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDBExpression_LeftOperand(), ecorePackage.getEObject(), null, "leftOperand", null, 0, 1, DBExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDBExpression_RightOperand(), ecorePackage.getEObject(), null, "rightOperand", null, 0, 1, DBExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yReadStatementEClass, YReadStatement.class, "YReadStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYReadStatement_Structs(), this.getYStructRefPair(), null, "structs", null, 0, -1, YReadStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadStatement_Joinclause(), this.getYJoin(), null, "joinclause", null, 0, 1, YReadStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadStatement_Whereclause(), theXbasePackage.getXExpression(), null, "whereclause", null, 0, 1, YReadStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadStatement_SuccessExpressions(), theXbasePackage.getXExpression(), null, "successExpressions", null, 0, -1, YReadStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYReadStatement_NotfoundExpressions(), theXbasePackage.getXExpression(), null, "notfoundExpressions", null, 0, -1, YReadStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yCreateStatementEClass, YCreateStatement.class, "YCreateStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYCreateStatement_Struct(), this.getYStructRefPair(), null, "struct", null, 0, 1, YCreateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYCreateStatement_SetExpressions(), theXbasePackage.getXExpression(), null, "setExpressions", null, 0, -1, YCreateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYCreateStatement_SuccessExpressions(), theXbasePackage.getXExpression(), null, "successExpressions", null, 0, -1, YCreateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYCreateStatement_AlreadyExistExpressions(), theXbasePackage.getXExpression(), null, "alreadyExistExpressions", null, 0, -1, YCreateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yWhereEClass, YWhere.class, "YWhere", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYWhere_Expression(), theXbasePackage.getXExpression(), null, "expression", null, 0, 1, YWhere.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotLengthEClass, YAnnotLength.class, "YAnnotLength", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotLength_Length(), ecorePackage.getEInt(), "length", null, 0, 1, YAnnotLength.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotMaxEClass, YAnnotMax.class, "YAnnotMax", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotMax_Length(), ecorePackage.getEInt(), "length", null, 0, 1, YAnnotMax.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotDecimalEClass, YAnnotDecimal.class, "YAnnotDecimal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotDecimal_Length(), ecorePackage.getEInt(), "length", null, 0, 1, YAnnotDecimal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getYAnnotDecimal_Decimal(), ecorePackage.getEInt(), "decimal", null, 0, 1, YAnnotDecimal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotDefaultEClass, YAnnotDefault.class, "YAnnotDefault", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(yAnnotActionEClass, YAnnotAction.class, "YAnnotAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotAction_Action(), ecorePackage.getEString(), "action", null, 0, 1, YAnnotAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yAnnotMessageEClass, YAnnotMessage.class, "YAnnotMessage", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getYAnnotMessage_Msg(), ecorePackage.getEString(), "msg", null, 0, 1, YAnnotMessage.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dbBinaryOperationEClass, DBBinaryOperation.class, "DBBinaryOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDBBinaryOperation_Feature(), theTypesPackage.getJvmIdentifiableElement(), null, "feature", null, 0, 1, DBBinaryOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(yAccessLevelEEnum, YAccessLevel.class, "YAccessLevel");
    addEEnumLiteral(yAccessLevelEEnum, YAccessLevel.PRIVATE);
    addEEnumLiteral(yAccessLevelEEnum, YAccessLevel.PROTECTED);
    addEEnumLiteral(yAccessLevelEEnum, YAccessLevel.PUBLIC);

    // Create resource
    createResource(eNS_URI);
  }

} //LangPackageImpl
