/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.lang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DB Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.DBExpression#getLeftOperand <em>Left Operand</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.DBExpression#getRightOperand <em>Right Operand</em>}</li>
 * </ul>
 *
 * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getDBExpression()
 * @model
 * @generated
 */
public interface DBExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Left Operand</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left Operand</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Operand</em>' reference.
   * @see #setLeftOperand(EObject)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getDBExpression_LeftOperand()
   * @model
   * @generated
   */
  EObject getLeftOperand();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.DBExpression#getLeftOperand <em>Left Operand</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left Operand</em>' reference.
   * @see #getLeftOperand()
   * @generated
   */
  void setLeftOperand(EObject value);

  /**
   * Returns the value of the '<em><b>Right Operand</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right Operand</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right Operand</em>' reference.
   * @see #setRightOperand(EObject)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getDBExpression_RightOperand()
   * @model
   * @generated
   */
  EObject getRightOperand();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.DBExpression#getRightOperand <em>Right Operand</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right Operand</em>' reference.
   * @see #getRightOperand()
   * @generated
   */
  void setRightOperand(EObject value);

} // DBExpression
