/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.lang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XExpression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getXExpression()
 * @model
 * @generated
 */
public interface XExpression extends org.eclipse.xtext.xbase.XExpression
{
} // XExpression
