/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.lang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>YAnnot Rel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YAnnotRel#isParent <em>Parent</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YAnnotRel#getName <em>Name</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YAnnotRel#isOptional <em>Optional</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YAnnotRel#getTarget <em>Target</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YAnnotRel#isMany <em>Many</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YAnnotRel#getInverse <em>Inverse</em>}</li>
 * </ul>
 *
 * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotRel()
 * @model
 * @generated
 */
public interface YAnnotRel extends YAnnotEntityInner, YAnnotIdInner
{
  /**
   * Returns the value of the '<em><b>Parent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parent</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent</em>' attribute.
   * @see #setParent(boolean)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotRel_Parent()
   * @model
   * @generated
   */
  boolean isParent();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YAnnotRel#isParent <em>Parent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent</em>' attribute.
   * @see #isParent()
   * @generated
   */
  void setParent(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotRel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YAnnotRel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Optional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Optional</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Optional</em>' attribute.
   * @see #setOptional(boolean)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotRel_Optional()
   * @model
   * @generated
   */
  boolean isOptional();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YAnnotRel#isOptional <em>Optional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Optional</em>' attribute.
   * @see #isOptional()
   * @generated
   */
  void setOptional(boolean value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(YAnnotEntity)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotRel_Target()
   * @model
   * @generated
   */
  YAnnotEntity getTarget();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YAnnotRel#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(YAnnotEntity value);

  /**
   * Returns the value of the '<em><b>Many</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Many</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Many</em>' attribute.
   * @see #setMany(boolean)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotRel_Many()
   * @model
   * @generated
   */
  boolean isMany();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YAnnotRel#isMany <em>Many</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Many</em>' attribute.
   * @see #isMany()
   * @generated
   */
  void setMany(boolean value);

  /**
   * Returns the value of the '<em><b>Inverse</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inverse</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inverse</em>' reference.
   * @see #setInverse(YAnnotRel)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotRel_Inverse()
   * @model
   * @generated
   */
  YAnnotRel getInverse();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YAnnotRel#getInverse <em>Inverse</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inverse</em>' reference.
   * @see #getInverse()
   * @generated
   */
  void setInverse(YAnnotRel value);

} // YAnnotRel
