/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.lang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>YAnnot Column</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YAnnotColumn#getAttrref <em>Attrref</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YAnnotColumn#getType <em>Type</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YAnnotColumn#getOptional <em>Optional</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YAnnotColumn#getAnnots <em>Annots</em>}</li>
 * </ul>
 *
 * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotColumn()
 * @model
 * @generated
 */
public interface YAnnotColumn extends EObject
{
  /**
   * Returns the value of the '<em><b>Attrref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attrref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attrref</em>' reference.
   * @see #setAttrref(YAnnotAttr)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotColumn_Attrref()
   * @model
   * @generated
   */
  YAnnotAttr getAttrref();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YAnnotColumn#getAttrref <em>Attrref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attrref</em>' reference.
   * @see #getAttrref()
   * @generated
   */
  void setAttrref(YAnnotAttr value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotColumn_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YAnnotColumn#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Optional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Optional</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Optional</em>' attribute.
   * @see #setOptional(String)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotColumn_Optional()
   * @model
   * @generated
   */
  String getOptional();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YAnnotColumn#getOptional <em>Optional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Optional</em>' attribute.
   * @see #getOptional()
   * @generated
   */
  void setOptional(String value);

  /**
   * Returns the value of the '<em><b>Annots</b></em>' containment reference list.
   * The list contents are of type {@link eu.jgen.notes.dmw.lite.lang.YAnnot}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Annots</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annots</em>' containment reference list.
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotColumn_Annots()
   * @model containment="true"
   * @generated
   */
  EList<YAnnot> getAnnots();

} // YAnnotColumn
