/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dmw.lite.lang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>YAnnot Technical Design</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YAnnotTechnicalDesign#getDatabase <em>Database</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YAnnotTechnicalDesign#getFeatures <em>Features</em>}</li>
 * </ul>
 *
 * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotTechnicalDesign()
 * @model
 * @generated
 */
public interface YAnnotTechnicalDesign extends EObject
{
  /**
   * Returns the value of the '<em><b>Database</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Database</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Database</em>' reference.
   * @see #setDatabase(YAnnotDatabase)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotTechnicalDesign_Database()
   * @model
   * @generated
   */
  YAnnotDatabase getDatabase();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YAnnotTechnicalDesign#getDatabase <em>Database</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Database</em>' reference.
   * @see #getDatabase()
   * @generated
   */
  void setDatabase(YAnnotDatabase value);

  /**
   * Returns the value of the '<em><b>Features</b></em>' containment reference list.
   * The list contents are of type {@link eu.jgen.notes.dmw.lite.lang.YAnnotTable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Features</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' containment reference list.
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYAnnotTechnicalDesign_Features()
   * @model containment="true"
   * @generated
   */
  EList<YAnnotTable> getFeatures();

} // YAnnotTechnicalDesign
