/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.lang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>YClass</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YClass#getSuperclass <em>Superclass</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YClass#getEntityRef <em>Entity Ref</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YClass#getMembers <em>Members</em>}</li>
 * </ul>
 *
 * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYClass()
 * @model
 * @generated
 */
public interface YClass extends YMember
{
  /**
   * Returns the value of the '<em><b>Superclass</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Superclass</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Superclass</em>' containment reference.
   * @see #setSuperclass(JvmTypeReference)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYClass_Superclass()
   * @model containment="true"
   * @generated
   */
  JvmTypeReference getSuperclass();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YClass#getSuperclass <em>Superclass</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Superclass</em>' containment reference.
   * @see #getSuperclass()
   * @generated
   */
  void setSuperclass(JvmTypeReference value);

  /**
   * Returns the value of the '<em><b>Entity Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entity Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Ref</em>' reference.
   * @see #setEntityRef(YAnnotEntity)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYClass_EntityRef()
   * @model
   * @generated
   */
  YAnnotEntity getEntityRef();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YClass#getEntityRef <em>Entity Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Ref</em>' reference.
   * @see #getEntityRef()
   * @generated
   */
  void setEntityRef(YAnnotEntity value);

  /**
   * Returns the value of the '<em><b>Members</b></em>' containment reference list.
   * The list contents are of type {@link eu.jgen.notes.dmw.lite.lang.YMember}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Members</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' containment reference list.
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYClass_Members()
   * @model containment="true"
   * @generated
   */
  EList<YMember> getMembers();

} // YClass
