/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.lang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmTypeReference;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>YFunction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YFunction#getAccess <em>Access</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YFunction#getParams <em>Params</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YFunction#getType <em>Type</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YFunction#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYFunction()
 * @model
 * @generated
 */
public interface YFunction extends YMember
{
  /**
   * Returns the value of the '<em><b>Access</b></em>' attribute.
   * The literals are from the enumeration {@link eu.jgen.notes.dmw.lite.lang.YAccessLevel}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Access</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Access</em>' attribute.
   * @see eu.jgen.notes.dmw.lite.lang.YAccessLevel
   * @see #setAccess(YAccessLevel)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYFunction_Access()
   * @model
   * @generated
   */
  YAccessLevel getAccess();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YFunction#getAccess <em>Access</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Access</em>' attribute.
   * @see eu.jgen.notes.dmw.lite.lang.YAccessLevel
   * @see #getAccess()
   * @generated
   */
  void setAccess(YAccessLevel value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.xtext.common.types.JvmTypeReference}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYFunction_Params()
   * @model containment="true"
   * @generated
   */
  EList<JvmTypeReference> getParams();

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(JvmTypeReference)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYFunction_Type()
   * @model containment="true"
   * @generated
   */
  JvmTypeReference getType();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YFunction#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(JvmTypeReference value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(XExpression)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYFunction_Body()
   * @model containment="true"
   * @generated
   */
  XExpression getBody();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YFunction#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(XExpression value);

} // YFunction
