/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.lang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>YParameter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYParameter()
 * @model
 * @generated
 */
public interface YParameter extends YSymbol
{
} // YParameter
