/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dmw.lite.lang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>YSuper</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYSuper()
 * @model
 * @generated
 */
public interface YSuper extends YExpression
{
} // YSuper
