/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.dmw.lite.lang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>YSwitch Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YSwitchCase#getCase <em>Case</em>}</li>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YSwitchCase#getThen <em>Then</em>}</li>
 * </ul>
 *
 * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYSwitchCase()
 * @model
 * @generated
 */
public interface YSwitchCase extends EObject
{
  /**
   * Returns the value of the '<em><b>Case</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Case</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Case</em>' containment reference.
   * @see #setCase(YExpression)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYSwitchCase_Case()
   * @model containment="true"
   * @generated
   */
  YExpression getCase();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YSwitchCase#getCase <em>Case</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Case</em>' containment reference.
   * @see #getCase()
   * @generated
   */
  void setCase(YExpression value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(YBlock)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYSwitchCase_Then()
   * @model containment="true"
   * @generated
   */
  YBlock getThen();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YSwitchCase#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(YBlock value);

} // YSwitchCase
