/**
 * generated by Xtext 2.15.0
 */
package eu.jgen.notes.dmw.lite.lang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>YWhere</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.jgen.notes.dmw.lite.lang.YWhere#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYWhere()
 * @model
 * @generated
 */
public interface YWhere extends XExpression
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(org.eclipse.xtext.xbase.XExpression)
   * @see eu.jgen.notes.dmw.lite.lang.LangPackage#getYWhere_Expression()
   * @model containment="true"
   * @generated
   */
  org.eclipse.xtext.xbase.XExpression getExpression();

  /**
   * Sets the value of the '{@link eu.jgen.notes.dmw.lite.lang.YWhere#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(org.eclipse.xtext.xbase.XExpression value);

} // YWhere
